/**
 * Vercel AI SDK telemetry attribute names.
 *
 * These constants are the **fallback** path the attribute mapper
 * reads from when the OTel GenAI primary path (`./conventions.ts`)
 * yields nothing. The Vercel AI SDK emits its own `ai.*` namespace
 * for spans generated by `streamText` / `generateText` /
 * `streamObject` / `generateObject` when
 * `experimental_telemetry: { isEnabled: true }` is set on the call.
 *
 * The names here are pinned from a real `streamText` run on Vercel
 * AI SDK 6.x with OpenAI as the provider — the actual span
 * attributes observed on the wire. If a future SDK version renames
 * or removes any of them, the mapper degrades gracefully (the field
 * comes through as `null` rather than crashing) and the primary
 * `gen_ai.*` path is expected to remain stable.
 *
 * Span name conventions (used to derive `metadata.streaming`):
 *
 *   - `ai.generateText.doGenerate`   non-streaming text/tool call
 *   - `ai.streamText.doStream`       streaming text/tool call
 *   - `ai.generateObject.doGenerate` non-streaming structured output
 *   - `ai.streamObject.doStream`     streaming structured output
 */

// ─── Model + provider ──────────────────────────────────────────────

/**
 * Model identifier as the user passed it, e.g. `'gpt-4o-mini'` or
 * `'claude-haiku-4-5'`.
 */
export const AI_MODEL_ID = 'ai.model.id'

/**
 * Provider identifier, **including** the sub-namespace when the
 * model has one — e.g. `'openai.responses'` for OpenAI Responses
 * API calls, `'openai.chat'` for chat-completions calls. The
 * attribute mapper extracts the base provider (`'openai'`) for
 * downstream filters and preserves the full surface in
 * `metadata.providerSurface` for debugging.
 */
export const AI_MODEL_PROVIDER = 'ai.model.provider'

// ─── Prompt + response ─────────────────────────────────────────────

/**
 * Prompt messages as a JSON-stringified array. Same shape as the
 * `messages` parameter the caller passed to `streamText` /
 * `generateText`.
 */
export const AI_PROMPT_MESSAGES = 'ai.prompt.messages'

/** Final assistant text response (joined across streamed chunks). */
export const AI_RESPONSE_TEXT = 'ai.response.text'

/**
 * Tool calls emitted in the response, as a JSON-stringified array
 * of `{ toolCallId, toolName, args }` objects (Vercel SDK shape).
 */
export const AI_RESPONSE_TOOL_CALLS = 'ai.response.toolCalls'

/**
 * Single stop reason on the response — `'stop'`, `'length'`,
 * `'tool-calls'`, etc. The Vercel SDK normalises across providers
 * to its own enum.
 */
export const AI_RESPONSE_FINISH_REASON = 'ai.response.finishReason'

// ─── Token usage ───────────────────────────────────────────────────

/** Prompt tokens. */
export const AI_USAGE_PROMPT_TOKENS = 'ai.usage.promptTokens'

/** Completion tokens. */
export const AI_USAGE_COMPLETION_TOKENS = 'ai.usage.completionTokens'

/** Cache-read tokens (OpenAI / Anthropic surfaces them both here). */
export const AI_USAGE_CACHED_INPUT_TOKENS = 'ai.usage.cachedInputTokens'

/**
 * Cache-write tokens (Anthropic ephemeral cache creation; absent on
 * OpenAI events as of this writing).
 */
export const AI_USAGE_CACHE_CREATION_INPUT_TOKENS =
  'ai.usage.cacheCreationInputTokens'
